const assert = require('assert')
const generateWebSocketKey = require('./generateWebSocketKey')

describe('generateWebSocketKey', () => {
  it('[async] Generates a WebSocket key for use in the Sec-WebSocket-Key header', async () => {
    assert.equal(typeof generateWebSocketKey().then, 'function')
    assert.equal(typeof await generateWebSocketKey(), 'string')
    const key1 = await generateWebSocketKey()
    assert.equal(key1.length, 24)
    const key2 = await generateWebSocketKey()
    assert.equal(key2.length, 24)
    const key3 = await generateWebSocketKey()
    assert.equal(key3.length, 24)
    const key4 = await generateWebSocketKey()
    assert.equal(key4.length, 24)
    const key5 = await generateWebSocketKey()
    assert.equal(key5.length, 24)
    assert.notEqual(key1, key2)
    assert.notEqual(key2, key3)
    assert.notEqual(key1, key3)
    assert.notEqual(key3, key4)
    assert.notEqual(key2, key4)
    assert.notEqual(key1, key4)
    assert.notEqual(key4, key5)
    assert.notEqual(key3, key5)
    assert.notEqual(key2, key5)
    assert.notEqual(key1, key5)
  })
})
